#!/usr/bin/env python
"""Block 64: do lens-subspace components propagate on their own?

Block 62: the projector paste through J plane + R top-256 injected a median 274 energy
over L8-20 at the bridge position and rescued 16/35 never-flipped items; the same-
dimension random subspace injected 643 and rescued 13. Hypothesis: components the model
reads are regenerated by its own computation at later layers, so a projector paste has
less left to inject there; unread components have to be re-injected at every layer.
Test (a): per-layer injected energy e_l of the multi-layer projector paste against the
static per-layer projected difference s_l = ||QQ^T(donor_l - clean_l)||^2. The ratio
e_l/s_l is the fraction that still had to be injected at layer l (1 = nothing propagated).
Test (b): paste at L8 ONLY (full / J+R256 / J+rand256 / J plane), then at L9-20 with no
further intervention measure the realised fraction of the donor difference
f_l = <h_l^int - h_l^clean, d_l>/||d_l||^2, its in-subspace version, and the flips.
Prediction: e_l/s_l falls with depth for the lens subspace and stays near 1 for the
random one; single-layer pastes through the lens subspace realise more of d_l downstream.
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

import torch
from transformer_lens.tools.analysis.jacobian_lens import _make_intervention_hook, _resid_post_hook_name

from q30_4b_replication import load_4b
from q35_donor_paste import find_last
from q51_subspace_ladder import orthonormal
from rlens.data import load_items
from rlens.forward import final_logprobs
from rlens.model import load_lenses, load_model
from rlens.paths import RESULTS_DIR, results_dir
from rlens.stages.common import eligible_hybrid, hybrid_rows, resolve_item
from rlens.tokens import encode_variant

BAND = list(range(8, 21))
FOURB = os.environ.get("MATS_MODEL", "9b") == "4b"  # block68: same test on Qwen3.5-4B
TEMPLATES = pathlib.Path(__file__).resolve().parent / "data" / "single_hop_templates.json"


def recording_projector_hooks(model, donors, layers, position, bases_by_layer, store):
    """h <- h + QQ^T(donor - h) at `position`; store[layer] = injected energy at that layer (Q=None: full)."""
    hooks = []
    for layer in layers:
        donor = donors[layer].float()
        q = None if bases_by_layer is None else bases_by_layer[layer].float()

        def transform(selected, donor=donor, q=q, layer=layer):
            h = selected.float()
            d = donor.to(h.device).expand_as(h) - h
            delta = d if q is None else (d @ q.to(h.device).T) @ q.to(h.device)
            store[layer] = float((delta ** 2).sum().item())
            return h + delta

        hooks.append((_resid_post_hook_name(layer), _make_intervention_hook(transform, [position], model.cfg.d_model)))
    return hooks


@torch.inference_mode()
def main() -> int:
    out_dir = results_dir("block68_4b_propagation" if FOURB else "block64_propagation")
    if FOURB:
        model, lenses = load_4b()
    else:
        model = load_model()
        lenses = load_lenses()
    lens = lenses["J"]
    items = load_items()
    templates = json.loads(TEMPLATES.read_text(encoding="utf-8"))
    clean_rows = json.loads((RESULTS_DIR / ("block27_4b" if FOURB else "block01") / "clean_rows.json").read_text(encoding="utf-8"))
    eligible = eligible_hybrid(clean_rows)
    modes = hybrid_rows(clean_rows)
    best_pos = {}
    for line in (RESULTS_DIR / ("block35_4b_donor_paste" if FOURB else "block31_donor_paste") / "donor_paste.jsonl").read_text().splitlines():
        r = json.loads(line)
        if r["position_set"] == "best" and r["arm"] == "clamp2d":
            best_pos[r["index"]] = int(r["position"])
    names = {layer: _resid_post_hook_name(layer) for layer in BAND}
    wanted = set(names.values())
    svd_R = {}
    for layer in BAND:
        j = lenses["R"].jacobians[layer].to(device=model.W_U.device, dtype=torch.float32)
        _, _, vh = torch.linalg.svd(j, full_matrices=False)
        svd_R[layer] = vh[:256]
    handle = (out_dir / "propagation.jsonl").open("w", encoding="utf-8")
    for n, index in enumerate(eligible):
        r = resolve_item(model.tokenizer, items[index], modes[index]["mode"])
        tokens = model.to_tokens(r.prompt, prepend_bos=False)
        a, s = r.answer.first_id, r.swap_answer.first_id
        ids = [r.src.first_id, r.tgt.first_id]
        if index not in best_pos or str(index) not in templates:
            continue
        position = best_pos[index]
        donor_text = templates[str(index)].format(r.item.swap_to)
        dt = model.to_tokens(donor_text, prepend_bos=False)
        dseq = dt[0].tolist()
        dpos = None
        for variant in (" " + r.item.swap_to, r.item.swap_to):
            dpos = find_last(dseq, list(encode_variant(model.tokenizer, variant).ids))
            if dpos is not None:
                break
        if dpos is None:
            continue
        _, dcache = model.run_with_cache(dt, names_filter=lambda x: x in wanted)
        donor = {layer: dcache[names[layer]][0, dpos] for layer in BAND}
        _, cache = model.run_with_cache(tokens, names_filter=lambda x: x in wanted)
        clean_h = {layer: cache[names[layer]][0, position].float() for layer in BAND}
        clean = final_logprobs(model, tokens)
        base = float(clean[s] - clean[a])
        bases = {l: lens.lens_vectors(model, ids, l).float() for l in BAND}
        gen = torch.Generator(device="cpu").manual_seed(index)
        subspaces = {
            "J_plane": {l: orthonormal(bases[l]) for l in BAND},
            "J+R256": {l: orthonormal(torch.cat([bases[l], svd_R[l].to(bases[l].device)])) for l in BAND},
            "J+rand256": {l: orthonormal(torch.cat([bases[l], torch.randn(256, model.cfg.d_model, generator=gen).to(bases[l].device)])) for l in BAND},
            "full": None,
        }
        d = {l: donor[l].float() - clean_h[l] for l in BAND}
        rec = {"index": index, "name": r.item.name, "position": position, "arms": {}}
        for sub_name, sub in subspaces.items():
            static = {}
            for l in BAND:
                proj = d[l] if sub is None else (d[l] @ sub[l].T) @ sub[l]
                static[l] = float((proj ** 2).sum().item())
            # (a) multi-layer paste with per-layer injected energy
            store = {}
            logp = final_logprobs(model, tokens, recording_projector_hooks(model, donor, BAND, position, sub, store))
            multi = {"delta_margin": float((logp[s] - logp[a]) - base), "top1_is_swap": int(logp.argmax().item()) == s,
                     "injected": [store[l] for l in BAND], "static": [static[l] for l in BAND]}
            # (b) paste at L8 only, read the downstream residuals at the same position
            hooks = recording_projector_hooks(model, donor, [BAND[0]], position, sub, {})
            with model.hooks(fwd_hooks=hooks):
                logits, icache = model.run_with_cache(tokens, names_filter=lambda x: x in wanted)
            lp = torch.log_softmax(logits[0, -1].float(), dim=-1)
            realised, realised_sub, moved = [], [], []
            for l in BAND:
                delta = icache[names[l]][0, position].float() - clean_h[l]
                realised.append(float((delta @ d[l]).item() / max(float((d[l] ** 2).sum().item()), 1e-9)))
                if sub is None:
                    realised_sub.append(realised[-1])
                else:
                    pd = (d[l] @ sub[l].T) @ sub[l]
                    pdelta = (delta @ sub[l].T) @ sub[l]
                    realised_sub.append(float((pdelta @ pd).item() / max(float((pd ** 2).sum().item()), 1e-9)))
                moved.append(float((delta ** 2).sum().item()))
            single = {"delta_margin": float((lp[s] - lp[a]) - base), "top1_is_swap": int(lp.argmax().item()) == s,
                      "realised": realised, "realised_sub": realised_sub, "moved_energy": moved,
                      "d_energy": [float((d[l] ** 2).sum().item()) for l in BAND]}
            rec["arms"][sub_name] = {"multi": multi, "single_L8": single}
        handle.write(json.dumps(rec) + "\n")
        if n % 10 == 0:
            print(f"[q68] {n + 1}/{len(eligible)}", flush=True)
    handle.close()
    print("[block68] done" if FOURB else "[block64] done", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
